version: "3.8"

services:
  # Postgres service
  postgres:
    image: postgres:latest
    container_name: yeetcode-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: yeetcode
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - yeetcode-network
    restart: unless-stopped

  # pgAdmin service
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: yeetcode-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - yeetcode-network
    restart: unless-stopped
networks:
  yeetcode-network:
    driver: bridge


volumes:
  postgres_data: